In [ ]:
import pandas as pd

# Load the Excel file
excel_path = r"C:\Users\Charbel\Desktop\Data Science X5\Data Collection - Registration App Final2.xlsx"
excel_file = pd.ExcelFile(excel_path)

# Read all sheets into a dictionary of DataFrames
sheets_dict = {sheet_name: excel_file.parse(sheet_name) for sheet_name in excel_file.sheet_names}

# Display sheet names and the first few rows of each sheet
{sheet: df.head() for sheet, df in sheets_dict.items()}

payment_method_df = sheets_dict["Payment_Method"]
payment_df = sheets_dict["Payment"]
institution_df = sheets_dict["Institution"]
academic_level_df = sheets_dict["Academic_Level"]
track_df = sheets_dict["Track"]
batch_df = sheets_dict["Batch"]
track_batch_df = sheets_dict["Track_Batch"]
user_batch_df = sheets_dict["User_Batch"]
instructor_batch_df = sheets_dict["Instructor_Batch"]
user_df = sheets_dict["USER"]

In [6]:
user_df.head()

,ID,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD,PHONE_NUMBER,DATE_OF_BIRTH,GENDER,ROLE,STATUS,HAS_PAID,CREATED_AT,UPDATED_AT,INSTITUTION_ID,ACADEMIC_LEVEL_ID
0,1,Sarah,Chang,sarah.chang@gmail.com,NtIxqr4_&0,961761679215,1994-10-31,Female,User,Inactive,1,2025-04-12 17:00:00,2025-04-12 17:00:00,33,4
1,2,Angela,Jefferson,angela.jefferson@gmail.com,^7Z3SKR%td,961767007071,2001-01-26,Female,User,Active,1,2025-04-12 17:00:00,2025-04-12 17:00:00,14,6
2,3,Gary,Cross,gary.cross@gmail.com,41_SGsqz+A,961715202798,2002-08-30,Male,User,Active,1,2025-04-12 17:00:00,2025-04-12 17:00:00,46,6
3,4,Joshua,Roberts,joshua.roberts@gmail.com,@9Zm#y7^m),961032237192,1997-08-04,Male,User,Active,1,2025-04-12 17:00:00,2025-04-12 17:00:00,31,4
4,5,Kelly,Boyd,kelly.boyd@gmail.com,$J8VZsyEC3,961764430567,1993-07-02,Female,User,Inactive,1,2025-04-12 17:00:00,2025-04-12 17:00:00,31,6

In [ ]:
# Clean and preprocess each DataFrame: drop duplicates and handle missing values (simple strategy: drop for now)

cleaned_dfs = {}
for name, df in sheets_dict.items():
    cleaned_df = df.drop_duplicates().dropna(how='all')  
    cleaned_dfs[name] = cleaned_df

# Assign each cleaned DataFrame to a variable
payment_method_df = cleaned_dfs["Payment_Method"]
payment_df = cleaned_dfs["Payment"]
institution_df = cleaned_dfs["Institution"]
academic_level_df = cleaned_dfs["Academic_Level"]
track_df = cleaned_dfs["Track"]
batch_df = cleaned_dfs["Batch"]
track_batch_df = cleaned_dfs["Track_Batch"]
user_batch_df = cleaned_dfs["User_Batch"]
instructor_batch_df = cleaned_dfs["Instructor_Batch"]
user_df = cleaned_dfs["USER"]

# Show the number of rows removed for each DataFrame
rows_removed = {
    name: len(sheets_dict[name]) - len(cleaned_dfs[name])
    for name in sheets_dict
}

rows_removed

{'Payment_Method': 0,
 'Payment': 0,
 'Institution': 0,
 'Academic_Level': 0,
 'Track': 0,
 'Batch': 0,
 'Track_Batch': 0,
 'User_Batch': 0,
 'Instructor_Batch': 0,
 'USER': 0}

In [8]:
# Check for null values in each DataFrame
null_counts = {
    name: df.isnull().sum()
    for name, df in cleaned_dfs.items()
}

# Filter to show only columns with nulls
null_columns_only = {
    name: counts[counts > 0]
    for name, counts in null_counts.items()
    if counts.sum() > 0
}

null_columns_only

{}

In [9]:
# preprocessing and data cleaning is now done